export const mockRecords = [
    {
        id: 1,
        url: 'www.example.com',
        description: 'Description for record 1',
        landlord: 'Landlord 1',
        rent: 1000,
        size: 50,
        rooms: 2,
        wbs: true,
        house_number: '10',
        neighbourhood: 'Neighbourhood 1',
        suburb: 'Suburb 1',
        road: 'Road 1',
        borough: 'Borough 1',
        lat: 52.520008,
        long: 13.404954,
        properties: 'Property details for record 1',
        createdAt: new Date(),
    },
    {
        id: 2,
        url: 'www.example2.com',
        description: 'Description for record 2',
        landlord: 'Landlord 2',
        rent: 1200,
        size: 60,
        rooms: 3,
        wbs: false,
        house_number: '20',
        neighbourhood: 'Neighbourhood 2',
        suburb: 'Suburb 2',
        road: 'Road 2',
        borough: 'Borough 2',
        lat: 52.520018,
        long: 13.404964,
        properties: 'Property details for record 2',
        createdAt: new Date(),
    },
    {
        id: 3,
        url: 'www.example3.com',
        description: 'Description for record 3',
        landlord: 'Landlord 3',
        rent: 1400,
        size: 70,
        rooms: 4,
        wbs: true,
        house_number: '30',
        neighbourhood: 'Neighbourhood 3',
        suburb: 'Suburb 3',
        road: 'Road 3',
        borough: 'Borough 3',
        lat: 52.520028,
        long: 13.404974,
        properties: 'Property details for record 3',
        createdAt: new Date(),
    },
    {
        id: 4,
        url: 'www.google.com',
        description: 'Hallo hier, geht übelst ab nummer 4',
        landlord: 'Bad Oscarshausen',
        rent: 200,
        size: 3,
        rooms: 3,
        wbs: false,
        house_number: '47',
        neighbourhood: '',
        suburb: '',
        road: 'Gubener Straße',
        borough: 'Friedrichshain-Kreuzberg',
        lat: 52.511924,
        long: 13.44999,
        properties:
            'aller guten dinge sind drei, aber zwei ist auch nicht schlecht',
        createdAt: new Date(),
    },
    {
        id: 5,
        url: 'www.example5.com',
        description: 'Description for record 5',
        landlord: 'Landlord 5',
        rent: 1600,
        size: 80,
        rooms: 5,
        wbs: false,
        house_number: '50',
        neighbourhood: 'Neighbourhood 5',
        suburb: 'Suburb 5',
        road: 'Road 5',
        borough: 'Borough 5',
        lat: 52.520038,
        long: 13.404984,
        properties: 'Property details for record 5',
        createdAt: new Date(),
    },
    {
        id: 6,
        url: 'www.example6.com',
        description: 'Description for record 6',
        landlord: 'Landlord 6',
        rent: 1800,
        size: 90,
        rooms: 6,
        wbs: true,
        house_number: '60',
        neighbourhood: 'Neighbourhood 6',
        suburb: 'Suburb 6',
        road: 'Road 6',
        borough: 'Borough 6',
        lat: 52.520048,
        long: 13.404994,
        properties: 'Property details for record 6',
        createdAt: new Date(),
    },
    {
        id: 7,
        url: 'www.example7.com',
        description: 'Description for record 7',
        landlord: 'Landlord 7',
        rent: 2000,
        size: 100,
        rooms: 7,
        wbs: false,
        house_number: '70',
        neighbourhood: 'Neighbourhood 7',
        suburb: 'Suburb 7',
        road: 'Road 7',
        borough: 'Borough 7',
        lat: 52.520058,
        long: 13.405004,
        properties: 'Property details for record 7',
        createdAt: new Date(),
    },
    {
        id: 8,
        url: 'www.example8.com',
        description: 'Description for record 8',
        landlord: 'Landlord 8',
        rent: 2200,
        size: 110,
        rooms: 8,
        wbs: true,
        house_number: '80',
        neighbourhood: 'Neighbourhood 8',
        suburb: 'Suburb 8',
        road: 'Road 8',
        borough: 'Borough 8',
        lat: 52.520068,
        long: 13.405014,
        properties: 'Property details for record 8',
        createdAt: new Date(),
    },
    {
        id: 9,
        url: 'www.example9.com',
        description: 'Description for record 9',
        landlord: 'Landlord 9',
        rent: 2400,
        size: 120,
        rooms: 9,
        wbs: false,
        house_number: '90',
        neighbourhood: 'Neighbourhood 9',
        suburb: 'Suburb 9',
        road: 'Road 9',
        borough: 'Borough 9',
        lat: 52.520078,
        long: 13.405024,
        properties: 'Property details for record 9',
        createdAt: new Date(),
    },
    {
        id: 10,
        url: 'www.example10.com',
        description: 'Description for record 10',
        landlord: 'Landlord 10',
        rent: 2600,
        size: 130,
        rooms: 10,
        wbs: true,
        house_number: '100',
        neighbourhood: 'Neighbourhood',
        suburb: 'Suburb',
        road: 'Road',
        borough: 'Borough',
        lat: 52.520088,
        long: 13.405034,
        properties: 'Property details for record 10',
        createdAt: new Date(),
    },
];
