import { prisma } from '../../../lib/prisma';

export const mockRecords = [
    {
        id: 1,
        url: 'www.google.com',
        description: 'Hallo hier, geht übelst ab nummer 1',
        landlord: 'Bad Oscarshausen',
        rent: 200,
        size: 3,
        rooms: 3,
        wbs: false,
        house_number: '47',
        neighbourhood: '',
        suburb: '',
        road: 'Gubener Straße',
        borough: 'Friedrichshain-Kreuzberg',
        lat: 52.511924,
        long: 13.44999,
        properties: 'aller guten dinge sind drei',
        createdAt: new Date(),
    },
    {
        id: 2,
        url: 'www.google.com',
        description: 'Hallo hier, geht übelst ab nummer 2',
        landlord: 'Bad Oscarshausen',
        rent: 200,
        size: 3,
        rooms: 3,
        wbs: false,
        house_number: '47',
        neighbourhood: '',
        suburb: '',
        road: 'Gubener Straße',
        borough: 'Friedrichshain-Kreuzberg',
        lat: 52.511924,
        long: 13.44999,
        properties: 'aller guten dinge sind drei',
        createdAt: new Date(),
    },
    {
        id: 3,
        url: 'www.google.com',
        description: 'Hallo hier, geht übelst ab nummer 3',
        landlord: 'Bad Oscarshausen',
        rent: 200,
        size: 3,
        rooms: 3,
        wbs: false,
        house_number: '47',
        neighbourhood: '',
        suburb: '',
        road: 'Gubener Straße',
        borough: 'Friedrichshain-Kreuzberg',
        lat: 52.511924,
        long: 13.44999,
        properties: 'aller guten dinge sind drei',
        createdAt: new Date(),
    },
    {
        id: 4,
        url: 'www.google.com',
        description: 'Hallo hier, geht übelst ab nummer 4',
        landlord: 'Bad Oscarshausen',
        rent: 200,
        size: 3,
        rooms: 3,
        wbs: false,
        house_number: '47',
        neighbourhood: '',
        suburb: '',
        road: 'Gubener Straße',
        borough: 'Friedrichshain-Kreuzberg',
        lat: 52.511924,
        long: 13.44999,
        properties: 'aller guten dinge sind drei',
        createdAt: new Date(),
    },
];
